version: "3.7"
services:
  azunyan:
    build: .
    image: azunyan
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    secrets:
      - source: conf_file
        target: azunyan_conf
    environment:
      - dbaddr=mongodb://database:27017
      - dbname=azunyan
      - webport=8080

  database:
    image: 'mongo'
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=azunyan
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
secrets:
  conf_file:
    file: "./azunyan.conf"
